window.TRANSLATIONS = {
            ca: {
                title: "Belén & Xevi · El nostre casament",
                names_title: "Belén i Xevi",
                hero_btn: "Veure detalls",
                menu_home: "Inici",
                menu_ubicaciones: "Ubicacions",
                menu_alojamiento: "On allotjar-se",
                cd_days: "Dies",
                cd_hours: "Hores",
                cd_minutes: "Minuts",
                cd_seconds: "Segons",
                detalls_titol: "Ens casem!",
                detalls_text: "Fa molt de temps que caminem junts, pero ara ha arribat el moment de fer el gran pas. Ens faria una il·lusió immensa que ens acompanyéssiu en aquest dia tan especial per a nosaltres.",
                detalls_cerimonia: "Cerimònia i Banquet",
                detalls_hora: "18:00h — Málaga",
                programa_titol: "Programa del dia",
                programa_text: "Aquest és l'horari previst per al gran dia. T'hi esperem!",
                prog_1: "<strong>Cerimònia</strong> al <span class=\"loc-link\" onclick=\"goToLocation('loc-santuario')\">Santuari de la Victòria de Màlaga</span>",
                prog_2: "<strong>Trasllat</strong> dels convidats a la finca <span class=\"loc-link\" onclick=\"goToLocation('loc-hacienda')\">Hacienda del Álamo</span>",
                prog_3: "<strong>Còctel</strong> de benvinguda",
                prog_4: "<strong>Sopar</strong>",
                prog_5: "<strong>Festa!</strong>",
                faq_titol: "Informació pràctica",
                faq_text: "Algunes preguntes habituals que us poden ser útils.",
                faq_q1: "Com arribar a l'església?",
                faq_a1: "<p>Si l'allotjament està a prop del santuari, recomanem anar-hi caminant. Si no, en transport públic, taxi o algun altre servei (Uber, Cabify, Bolt, etc).</p><p>El cotxe particular és una opció, però és difícil aparcar per la zona.</p>",
                faq_q2: "Com anar de l'església a la finca?",
                faq_a2: "<p>Hi haurà servei d'autobús que sortirà un cop acabada la cerimònia.</p><p>També es pot anar amb cotxe particular i aparcar a la finca, on hi ha una zona de parking habilitada.</p>",
                faq_q_bus: "Hi haurà autobús després de la festa?",
                faq_a_bus: "<p>Sí! Hi haurà servei d'autobús una vegada finalitzada la festa, que anirà de la finca al centre.</p><p>Si sou un grup de gent que s'allotja lluny del centre, parleu amb els nuvis per veure si és possible afegir una parada extra de l'autobús en aquesta ubicació.</p>",
                faq_q3: "Puc anar amb acompanyant o fills/es?",
                faq_a3: "<p>Per descomptat! Tothom és benvingut al nostre casament.</p><p>Recordeu apuntar-los al formulari d'inscripció.</p>",
                faq_q4: "Hi ha codi de vestimenta?",
                faq_a4: "<p>Animem tots els convidats a anar elegants i còmodes alhora.</p><p>Per a la festa, recomanem portar un calçat de recanvi que sigui més còmode per aguantar el màxim de temps possible.</p>",
                faq_q5: "I si volem fer un regal?",
                faq_a5: "<p>El millor regal és compartir el dia amb vosaltres.</p><p>Si a més voleu fer una aportació, ens seria de gran ajuda per a la nostra lluna de mel:</p><p>IBAN: ES80 1583 0001 1791 4883 1300</p>",
                rsvp_titol: "Confirmació d'assistència",
                rsvp_text: "Si us phau, confirma la teva assistència abans de l'1 de Juny.",
                rsvp_loading: "Carregant formulari...",
                rsvp_f_nombre: "Nom complet",
                rsvp_f_asistencia: "Hi assistiràs?",
                rsvp_si: "Sí",
                rsvp_no: "No",
                rsvp_f_acomp: "Vindràs amb acompanyant i/o fills/es?",
                rsvp_f_acomp_nombres: "Noms dels acompanyants",
                rsvp_f_acomp_hint: "Indica'ns també l'edat si són menors",
                rsvp_f_alergias: "Al·lèrgies, intoleràncies o restriccions alimentàries",
                rsvp_f_cancion: "Una cançó que no pot faltar a la festa",
                rsvp_enviar: "Enviar",
                rsvp_note: "Podràs tornar a enviar el formulari si necessites corregir alguna dada.",
                rsvp_success: "Gràcies! Hem rebut la teva confirmació.",
                footer_text: "Creat amb ♥",
                ubic_titol: "Ubicacions",
                ubic_text: "Aquí trobaràs les dues ubicacions del gran dia: la cerimònia i el banquet.",
                ubic_santuario_titol: "Cerimònia · Santuari de la Victòria",
                ubic_hacienda_titol: "Banquet · Hacienda del Álamo",
                ubic_preboda_titol: "Pre-boda · Restaurante Molabassa",
                ubic_abrir_maps: "Obrir a Google Maps",
                aloj_titol: "On allotjar-se",
                aloj_text: "Si véns de fora de Màlaga, aquí tens algunes recomanacions de zones i hotels per triar allotjament.",
                aloj_apartamentos: "Per a grups i famílies, recomanem llogar apartaments turístics en aquestes zones recomanades.",
                zona_centro_titol: "Centre · Carrer Larios",
                zona_centro_text: "La zona més cèntrica i amb encant, a prop de la Catedral i a deu minuts de la finca en cotxe.",
                zona_soho_titol: "El Soho",
                zona_soho_text: "Barri modern i artístic, tocant al centre històric i a la zona del port, amb ambient jove.",
                zona_malagueta_titol: "La Malagueta",
                zona_malagueta_text: "Vora la platja i a deu minuts a peu del centre històric, una opció més tranquil·la.",
                zona_huelin_titol: "Huelin",
                zona_huelin_text: "Allunyada del centre, però molt a prop de la platja. Sol sortir més econòmica.",
                zona_pedregalejo_titol: "Pedregalejo",
                zona_pedregalejo_text: "Allunyada del centre, però molt a prop de la platja i del restaurant de la pre-boda. Sol sortir més econòmica.",
                hotel_list_titol: "Algunes recomanacions",
                hotel_palacio_zona: "Centre — al costat de la Catedral, piscina a l'àtic",
                hotel_molina_zona: "Centre — terrassa amb vistes a la Catedral",
                hotel_solecio_zona: "Centre històric — palau del segle XVIII, 5 estrelles",
                hotel_bahia_zona: "El Soho — terrassa amb bar, bon ambient",
                hotel_equitativa_zona: "El Soho — edifici emblemàtic al carrer Larios",
                hotel_colon_zona: "Centre — a prop del carrer Larios i la Catedral",
                hotel_lasvegas_zona: "La Malagueta — davant la platja",
                hotel_tinta_zona: "Centre històric — palauet restaurat, molt cèntric",
                hotel_miramar_zona: "La Malagueta — davant la platja, 5 estrelles",
                hotel_me_zona: "Centre — al costat de la Plaça de la Mercè, piscina infinity a l'àtic"
            },
            es: {
                title: "Belén & Xevi · Nuestra boda",
                names_title: "Belén y Xevi",
                hero_btn: "Ver detalles",
                menu_home: "Inicio",
                menu_ubicaciones: "Ubicaciones",
                menu_alojamiento: "Dónde alojarse",
                cd_days: "Días",
                cd_hours: "Horas",
                cd_minutes: "Minutos",
                cd_seconds: "Segundos",
                detalls_titol: "¡Nos casamos!",
                detalls_text: "Hace mucho tiempo que caminamos juntos, pero ahora ha llegado el momento de dar el gran paso. Nos haría una ilusión inmensa que nos acompañarais en este día tan especial para nosotros.",
                detalls_cerimonia: "Ceremonia y Banquete",
                detalls_hora: "18:00h — Málaga",
                programa_titol: "Programa del día",
                programa_text: "Este es el horario previsto para el gran día. ¡Te esperamos!",
                prog_1: "<strong>Ceremonia</strong> en el <span class=\"loc-link\" onclick=\"goToLocation('loc-santuario')\">Santuario de la Victoria de Málaga</span>",
                prog_2: "<strong>Traslado</strong> de los invitados a la finca <span class=\"loc-link\" onclick=\"goToLocation('loc-hacienda')\">Hacienda del Álamo</span>",
                prog_3: "<strong>Cóctel</strong> de bienvenida",
                prog_4: "<strong>Cena</strong>",
                prog_5: "<strong>¡Fiesta!</strong>",
                faq_titol: "Información práctica",
                faq_text: "Algunas preguntas habituales que os pueden ser útiles.",
                faq_q1: "¿Cómo llegar a la iglesia?",
                faq_a1: "<p>Si el alojamiento está cerca del santuario, recomendamos ir andando. Si no, en transporte público, taxi o algún otro servicio (Uber, Cabify, Bolt, etc).</p><p>El coche particular es una opción, pero es difícil aparcar por la zona.</p>",
                faq_q2: "¿Cómo ir de la iglesia a la finca?",
                faq_a2: "<p>Habrá servicio de autobús que saldrá una vez finalizada la ceremonia.</p><p>También se puede ir en coche particular y aparcar en la finca, donde hay una zona de parking habilitada.</p>",
                faq_q_bus: "¿Habrá autobús después de la fiesta?",
                faq_a_bus: "<p>¡Sí! Habrá servicio de autobús una vez finalizada la fiesta, que irá de la finca al centro.</p><p>Si sois un grupo de gente que se aloja lejos del centro, hablad con los novios para ver si es posible añadir una parada extra del autobús en esa ubicación.</p>",
                faq_q3: "¿Puedo ir con acompañante o hijos/as?",
                faq_a3: "<p>¡Por supuesto! Todo el mundo es bienvenido a nuestra boda.</p><p>Recordad apuntarlos en el formulario de inscripción.</p>",
                faq_q4: "¿Hay código de vestimenta?",
                faq_a4: "<p>Animamos a todos los invitados a ir elegantes y cómodos al mismo tiempo.</p><p>Para la fiesta, recomendamos llevar calzado de recambio que sea más cómodo para durar lo máximo posible.</p>",
                faq_q5: "¿Y si queremos hacer un regalo?",
                faq_a5: "<p>El mejor regalo es compartir el día con vosotros.</p><p>Si además queréis hacer una aportación, nos sería de gran ayuda para nuestra luna de miel:</p><p>IBAN: ES80 1583 0001 1791 4883 1300</p>",
                rsvp_titol: "Confirmación de asistencia",
                rsvp_text: "Por favor, confirma tu asistencia antes del 1 de Junio.",
                rsvp_loading: "Cargando formulario...",
                rsvp_f_nombre: "Nombre completo",
                rsvp_f_asistencia: "¿Asistirás?",
                rsvp_si: "Sí",
                rsvp_no: "No",
                rsvp_f_acomp: "¿Vendrás con acompañante y/o hijos/as?",
                rsvp_f_acomp_nombres: "Nombres de los acompañantes",
                rsvp_f_acomp_hint: "Indícanos también la edad si son menores",
                rsvp_f_alergias: "Alergias, intolerancias o restricciones alimentarias",
                rsvp_f_cancion: "Una canción que no puede faltar en la fiesta",
                rsvp_enviar: "Enviar",
                rsvp_note: "Podrás volver a enviar el formulario si necesitas corregir algún dato.",
                rsvp_success: "¡Gracias! Hemos recibido tu confirmación.",
                footer_text: "Creado con ♥",
                ubic_titol: "Ubicaciones",
                ubic_text: "Aquí encontrarás las dos ubicaciones del gran día: la ceremonia y el banquete.",
                ubic_santuario_titol: "Ceremonia · Santuario de la Victoria",
                ubic_hacienda_titol: "Banquete · Hacienda del Álamo",
                ubic_preboda_titol: "Pre-boda · Restaurante Molabassa",
                ubic_abrir_maps: "Abrir en Google Maps",
                aloj_titol: "Dónde alojarse",
                aloj_text: "Si vienes de fuera de Málaga, aquí tienes algunas recomendaciones de zonas y hoteles para elegir alojamiento.",
                aloj_apartamentos: "Para grupos y familias, recomendamos alquilar apartamentos turísticos en estas zonas recomendadas.",
                zona_centro_titol: "Centro · Calle Larios",
                zona_centro_text: "La zona más céntrica y con encanto, cerca de la Catedral y a diez minutos de la finca en coche.",
                zona_soho_titol: "El Soho",
                zona_soho_text: "Barrio moderno y artístico, junto al centro histórico y al puerto, con ambiente joven.",
                zona_malagueta_titol: "La Malagueta",
                zona_malagueta_text: "Junto a la playa y a diez minutos a pie del centro histórico, una opción más tranquila.",
                zona_huelin_titol: "Huelin",
                zona_huelin_text: "Alejada del centro, pero muy cerca de la playa. Suele salir más económica.",
                zona_pedregalejo_titol: "Pedregalejo",
                zona_pedregalejo_text: "Alejada del centro, pero muy cerca de la playa y del restaurante de la pre-boda. Suele salir más económica.",
                hotel_list_titol: "Algunas recomendaciones",
                hotel_palacio_zona: "Centro — junto a la Catedral, piscina en la azotea",
                hotel_molina_zona: "Centro — terraza con vistas a la Catedral",
                hotel_solecio_zona: "Centro histórico — palacio del siglo XVIII, 5 estrellas",
                hotel_bahia_zona: "El Soho — terraza con bar, buen ambiente",
                hotel_equitativa_zona: "El Soho — edificio emblemático en la calle Larios",
                hotel_colon_zona: "Centro — cerca de la calle Larios y la Catedral",
                hotel_lasvegas_zona: "La Malagueta — frente a la playa",
                hotel_tinta_zona: "Centro histórico — palacete restaurado, muy céntrico",
                hotel_miramar_zona: "La Malagueta — frente a la playa, 5 estrellas",
                hotel_me_zona: "Centro — junto a la Plaza de la Merced, piscina infinity en la azotea"
            }
        };
